### ISSUE TITLE
SetTimeOut error in GraphQL

### ISSUE THREAD

**Issue by howdyhyber** [realm/realm-graphql-service#52]
I have seen in the logs something like this.

0|npm      | { FetchError: network timeout at: http://127.0.0.1:35853/xeleqt-production/realms/files/%2Fxeleqt-production
0|npm      |     at Timeout._onTimeout (/home/ec2-user/xeleqt-object-server/node_modules/node-fetch/index.js:126:13)
0|npm      |     at ontimeout (timers.js:482:11)
0|npm      |     at tryOnTimeout (timers.js:317:5)
0|npm      |     at Timer.listOnTimeout (timers.js:277:5)
0|npm      |   name: 'FetchError',
0|npm      |   message: 'network timeout at: http://127.0.0.1:35853/xeleqt-production/realms/files/%2Fxeleqt-production',
0|npm      |   type: 'request-timeout' }

"0|npm      |   message: 'network timeout at: http://127.0.0.1:35853/xeleqt-production/realms/files/%2Fxeleqt-production',"

whats with this link ? http://127.0.0.1:35853/xeleqt-production/realms/files/%2Fxeleqt-production

**Comment by nirinchev** [comment]
This is benign error that should be fixed with ROS 3.6.6.

**Comment by howdyhyber** [comment]
Good morning @nirinchev !

Im using the latest ROS and graphql, i still see this error.
